### ISSUE TITLE
Source Code not Compatible with Opencv 4 higher

### ISSUE THREAD

**Issue by entcat** [bbenligiray/stag#29] opened 2023-02-06 10:20 UTC
Hi,

I am trying to build the source on my windows system and i have a opencvconfig,cmake file from my opencv 4.x.x build. As i am looking at the source code, i can see there are lots of #ifndef BUILD_MACOS provided and some files are even using highly deprecated headers like opencv/cv.h, can you please make the source opencv 4 and higher compatible along with windows ?

Thanks.

**Comment by ManfredStoiber** [comment] 2023-11-20 13:29
Hi there,
I created an updated fork of this repository which is compatible with OpenCV 4, available [here](https://github.com/ManfredStoiber/stag).

@bbenligiray Since you mentioned that you won't be able to maintain this codebase, I decided to create a fork which I will keep updated and implement some more functionality. If you want me to create PRs for this repository instead, please let me know.

Best regards

**Comment by bbenligiray** [comment] 2023-11-22 16:39
Hey @ManfredStoiber, thanks for the offer but I think me being involved will only slow things down. You have my full blessing to maintain your fork and feel free to open a PR to update the README here to notify people of your fork.

**Comment by ManfredStoiber** [comment] 2023-12-14 03:27
I understand that. Thank you very much! I created a PR for the README as you suggested.

**Comment by bbenligiray** [comment] 2023-12-14 12:43
Closed by https://github.com/bbenligiray/stag/pull/33

**Closed by bbenligiray** 2023-12-14 12:43 UTC

**Comment by HRS-Soumya** [comment] 2023-12-20 06:58
> I understand that. Thank you very much! I created a PR for the README as you suggested.

Hi @ManfredStoiber. I tried building the library on windows using Cmake but i am getting an error where 'LibStag.lib' is not getting generated. I am facing the same error using cmake gui as well as the executeable.

**Comment by ManfredStoiber** [comment] 2023-12-21 05:24
Hi @HRS-Soumya,

I was able to reproduce your problem and fixed it. Please try again with the new version and let me know if it worked.

**Comment by HRS-Soumya** [comment] 2023-12-21 06:19
Hey @ManfredStoiber The build issue is resolved. But I found out that the release and the debug libs have the same name. Generally the debug libs have the name $name$d.lib and the release libs have the name $name$.lib. 
Also no staglib.dll file got generated. 
Can i add this library to my project without a dll file for this library ?

**Comment by HRS-Soumya** [comment] 2023-12-21 12:14
Nvm. It is working as expected. You created a static lib so the .dll file was not required. Thanks @ManfredStoiber.

**Comment by ManfredStoiber** [comment] 2023-12-21 13:34
Great! For Windows I added the "d"-Postfix for the library when compiled in debug mode, as you suggested.
You're right, the library is created as static by default, but I added the possibility to create as shared library when using the cmake option "BUILD_SHARED_LIBS=ON".

**Comment by bbenligiray** [comment] 2023-12-26 15:49
(@ManfredStoiber consider [enabling issues](https://stackoverflow.com/a/16406283) at your repo)

**Comment by ManfredStoiber** [comment] 2023-12-27 09:50
Thanks for the hint, I enabled it. Did not know it wasn't enabled by default.
